#!/bin/bash

# You can `source` this file in your shell to use a local Node.js installation
# to run/test the application without pushing to Bluemix

export WATSON_USERNAME=<insert Watson Conversation service ID>
export WATSON_PASSWORD=<insert Watson Conversation service password>

export CONV_WORKSPACE_ID=<insert Conversation workspace ID>
